import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Poppins } from "next/font/google";
import { BlogProvider } from "./context/Context";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./components/Footer";


const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <BlogProvider>
            <Navbar />

            {children}
<Footer/>
          
          </BlogProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
